### PR TITLE
sy-add missing tests

### PR DESCRIPTION
**Pull request by simonyu01**
Added missing frontend tests for UCSBSubjectsCreatePage and UCSBSubjectsIndexPage

### CODE REVIEW

**Comment by simonyu01** [comment]
Added new frontend tests to cover the create and index placeholder pages for collegiate subreddit

**Comment by rawenger** [comment]
looks like the mutation tests still aren't passing, we should wait till they are before merging

**Comment by simonyu01** [comment]
> looks like the mutation tests still aren't passing, we should wait till they are before merging

like wait for the surviving mutations to die of natural causes???

**Comment by rawenger** [comment]
um no since that would take literally forever. we should wait till someone fixes the tests that are failing to kill them

**Comment by simonyu01** [comment]
> um no since that would take literally forever. we should wait till someone fixes the tests that are failing to kill them

💩

**Review by rawenger — CHANGES_REQUESTED** [review]
Yeah I don't really think it makes sense to merge this if the whole point is to have all CI tests pass...even if this fixes some we might as well just wait till they all work

**Pull request merged**
