### PR TITLE
Earthquake List Page

### LINKED ISSUE #26: Implement List page for Earthquakes
Implement List page for Earthquakes 

Implement the List page using the Table component made in a previous issue.  

No need for the Edit and Delete columns. 

You may use the UCSBStudentsIndexPage as a model.

- [x] When loading the page, it fetches data from the backend and populates the table
- [x] test coverage is 100% for `npm run coverage`
- [x] test coverage is 100% for `npx stryker run`

### PR DESCRIPTION
**Pull request by vickyzhoujy**
# Overview

just did the list page, everything looks fine, if you log in with admin, go to swagger UI and use retrieve to get the data from USGS, the list will then show up on earthquake - list, like this:
Screen Shot 2022-02-23 at 2 52 50 PM

# Issues Addressed

finished issue #26 

# Details

Where applicable, include "before" and "after" screenshots or animated GIFs.   The tool [LiceCAP](https://www.cockos.com/licecap/) or one of [these similar tools](https://www.nextofwindows.com/5-free-tools-to-screen-capture-to-gif-on-windows) 
can be used to capture screenshots/animated GIFs.

## Reminders (delete this section before merging or as code is merged)
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

### CODE REVIEW

**Review by simonyu01 — CHANGES_REQUESTED** [review]
Earthquake List currently does not work on Heroku. Not sure what the problem is tho.

**Comment by lzbtharmstrong** [comment]
The page only shows up for a second and then turns white when I try to look at it on heroku, I had this issue before and it was because I typed one of the URIs wrong.

**Review by lzbtharmstrong — CHANGES_REQUESTED** [review]
Probably has a problem with the URIs for fetching from the backend, the page doesn't show up on github

**Comment by vickyzhoujy** [comment]
> Probably has a problem with the URIs for fetching from the backend, the page doesn't show up on github

Yes, I believe the problem is that the backend "get" hasn't been implemented yet. Should I wait until it gets implemented or should I merge the front end now

**Comment by vickyzhoujy** [comment]
@rawenger if you are busy, I can do the add list earthquake for you since it is needed for my frontend to load.

**Review by allisonhuang2 — CHANGES_REQUESTED** [review]
It looks like it's /api/earthquakes/retrieve instead of /api/earthquakes/all (?)

**Comment by vickyzhoujy** [comment]
> It looks like it's /api/earthquakes/retrieve instead of /api/earthquakes/all (?)

it is just the /api/earthquakes/all hasn't been implemented yet ;)

**Comment by oliviagillam** [comment]
Works on heroku! Should be good

**Pull request merged**
